name: 'qversity'
version: '1.0.0'
config-version: 2

profile: 'qversity'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  qversity:
    # Silver layer - cleaned and transformed data
    silver:
      +materialized: table
      +schema: silver
    # Gold layer - business-ready data marts
    gold:
      +materialized: table
      +schema: gold

# seeds:
  # qversity:
    # +schema: raw
