version: 2

models:
  - name: silver_mobile_customers
    description: >
      Flat table with customer information, extracted and cleaned from raw JSON. 
      This table contains one row per customer, uniquely identified by the surrogate key,
      customer_sk. City is linked via city_sk.
    columns:
      - name: customer_sk
        description: Surrogate key
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name

      - name: last_name
        description: Customer's last name

      - name: email
        description: Customer's email address

      - name: phone_number
        description: Customer's phone number
        tests:
          - not_null

      - name: age
        description: Customer's age (expected to be between 0 and 110, or null if unknown/nva

      - name: city_sk
        description: Foreign key referencing silver_cities table
        tests:
          - not_null
          - relationships:
              to: ref('silver_cities')
              field: city_sk

      - name: country_raw
        description: Original country extracted from raw JSON.

      - name: operator
        description: Mobile operator
        tests:
          - accepted_values:
              values: ['Claro', 'Movistar', 'Tigo', 'WOM']
              config:
                severity: warn

      - name: plan_type
        description: Type of mobile plan
        tests:
          - accepted_values:
              values: ['control', 'pospago', 'prepago']
              config:
                severity: warn

      - name: monthly_data_gb
        description: Monthly data allowance in gigabytes

      - name: data_usage_current_month
        description: Data usage in the current month (in GB)

      - name: monthly_bill_usd
        description: Monthly bill amount in USD

      - name: registration_date
        description: Date when the customer registered

      - name: last_payment_date
        description: Date of most recent payment

      - name: status
        description: Customer status
        tests:
          - accepted_values:
              values: ['active', 'inactive', 'suspended', 'valid', 'invalid']
              config:
                severity: warn

      - name: device_brand
        description: Brand of the customer's device

      - name: device_model
        description: Model of the customer's device

      - name: credit_limit
        description: Credit limit assigned to the customer

      - name: credit_score
        description: Numerical credit score of the customer (between 300 and 850)

  - name: silver_payment_history
    description: Flattened payment history records for each customer
    columns:
      - name: customer_sk
        description: Reference to the customer
        tests:
          - relationships:
              to: ref('silver_mobile_customers')
              field: customer_sk

      - name: date
        description: Date of the payment attempt

      - name: status
        description: Status of the payment
        tests:
          - accepted_values:
              values: ['failed', 'late', 'paid', 'pending']
              config:
                severity: warn

      - name: amount
        description: Payment amount in USD (nonnegative)

  - name: silver_contracted_services
    description: One row per customer and contracted service
    columns:
      - name: customer_sk
        description: Reference to the customer
        tests:
          - relationships:
              to: ref('silver_mobile_customers')
              field: customer_sk

      - name: service
        description: Contracted service
        tests:
          - accepted_values:
              values: ['DATA', 'INTERNATIONAL', 'ROAMING', 'SMS', 'VOICE']
              config:
                severity: warn

  - name: silver_cities
    description: Unique locations identified by city
    columns:
      - name: city_sk
        description: Surrogate key
        tests:
          - unique
          - not_null

      - name: name
        description: City name
        tests:
          - not_null

      - name: country
        description: ISO-3 country code
        tests:
          - not_null

      - name: latitude
        description: City's latitude

      - name: longitude
        description: City's longitude

sources:
  - name: bronze
    schema: bronze # The schema where Airflow loads the raw table
    tables:
      - name: bronze_mobile_customers